### ISSUE TITLE
Create Mini Map

### ISSUE THREAD

**Issue by jermbo** [jermbo/CosmicTyper#16]
I think it would be a great tool to visualize the code you are building while completing tasks.

Lesson 5 is a great example of how this would be enhanced. Lesson 5 walks you through building a flex box display and a handful of its properties. One thing students might get hung up on is the visualization of how the actual code is put together. So, in addition to the display of what is going on in the paint, we need to have a visual of the output code on either right or left side of the output.

**Comment by Lynne-Daniels** [comment]
https://github.com/jermbo/CosmicTyper/pull/38 is a basic implementation.  Maybe one day, take it further using a Codepen integration?  https://blog.codepen.io/documentation/prefill-embeds/

**Comment by jermbo** [comment]
Svelte update allowed for easy implementation for this. It could use enhancements, but basic functionality is present.
